// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1GzNR1BVFUIeWkTjE9W9Iq19mVpAz7FA',
    appId: '1:305098677657:web:190374a3158a6b95bc0708',
    messagingSenderId: '305098677657',
    projectId: 'treepet-e4a36',
    authDomain: 'treepet-e4a36.firebaseapp.com',
    storageBucket: 'treepet-e4a36.appspot.com',
    measurementId: 'G-DBEWSQCQQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1GzNR1BVFUIeWkTjE9W9Iq19mVpAz7FA',
    appId: '1:305098677657:android:84006637149cc694bc0708',
    messagingSenderId: '305098677657',
    projectId: 'treepet-e4a36',
    storageBucket: 'treepet-e4a36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1GzNR1BVFUIeWkTjE9W9Iq19mVpAz7FA',
    appId: '1:305098677657:ios:ab8ee5cbec179555bc0708',
    messagingSenderId: '305098677657',
    projectId: 'treepet-e4a36',
    storageBucket: 'treepet-e4a36.appspot.com',
    iosClientId: '305098677657-pqf3bdk5c5jta1groa2hi9c66ffuphqu.apps.googleusercontent.com',
    iosBundleId: 'kr.treepet.treepet',
  );
}
